config/routes.rb
Rails.application.routes.draw do
  root 'pages#splash' 
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  devise_for :users
  resources :users
  resources :groups do
    resources :expenses
  end
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_expenses, dependent: :destroy
  has_many :expenses, through: :group_expenses, dependent: :destroy
  belongs_to :user
  has_one_attached :icon_image

  validates :user_id, presence: true
  validates :name, presence: true
  validates :name, length: { minimum: 3 }
  validates_uniqueness_of :name, scope: :user_id, message: ' already exist'

  validate :acceptable_image
  def acceptable_image
    return unless icon_image.attached?

    errors.add(:icon_image, 'is too big') unless icon_image.byte_size <= 1.megabyte

    acceptable_types = ['image/jpeg', 'image/png']
    return if acceptable_types.include?(icon_image.content_type)

    errors.add(:icon_image, 'must be a JPEG or PNG')
  end

  def total_expenses_amount
    expenses.sum(:amount)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  load_and_authorize_resource
  rescue_from CanCan::AccessDenied do |_exception|
    flash[:alert] = 'You are not authorized to proceed with your request.'
    redirect_to root_path # You can redirect to any page you prefer
  end

  def index
    @groups = Group.includes(:expenses).where(user_id: current_user.id)
  end

  def show; end

  def new
    @group = Group.new
  end

  def create
    @group = current_user.groups.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to groups_url, notice: 'Group was successfully created.' }
        format.json { render :index, status: :created, location: @group }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @group = Group.find_by_id(params[:id])
  end

  def update
    @group = Group.find_by_id(params[:id])

    if @group.update(group_params)
      redirect_to @group
    else
      render :edit
    end
  end

  def destroy
    @group = Group.find_by_id(params[:id])
    @group.destroy

    respond_to do |format|
      if @group.destroy
        format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      else
        format.html { redirect_to groups_url, notice: 'Group was not destroyed.' }
      end
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_group
    @group = Group.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def group_params
    params.require(:group).permit(:name, :icon, :icon_image)
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_with(model: group) do |form| %>
<div class='container'>
  <% if group.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
        <% group.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-group my-2">
  
    <%= form.text_field :name, class: "form-control", placeholder: 'Enter Group Name' %>
  </div>

  <div class="input-group my-2">
  
    <%= form.text_field :icon, class: "form-control", placeholder: 'Enter Icon' %>
  </div>
  <div class="input-group my-2">
    <%= form.label :icon_image %>
    <%= form.file_field :icon_image, class: "form-control" %>
  </div>
</div>
  <div class="button-container">
    <%= form.submit "Save", class: "btn btn custom " %>
  </div>
<% end %>

app/views/groups/_group.html.erb
<div class='card-container'>
  
    <% if group.present?%>
      <% if group.icon_image.present? %>
        <%= image_tag group.icon_image.variant(resize_to_limit: [100, nil]) %>
      <% end %>
        
      <div class="group-list-item">
        <p class='title' ><%= group.name %></p>
        <p class='date'> <%= group.created_at.strftime('%e %B %Y') %></p>
      </div>
      <p>View your Total spending</p>
    <% else %>
      <h3>You haven't spend anything on this category yet</h3>
    <% end %>
    
</div>

app/views/groups/edit.html.erb
<%= render "form", group: @group %>

<br>

<div>
  <%= link_to "Show this group", @group %> |
  <%= link_to "Back to groups", groups_path %>
</div>

app/views/groups/index.html.erb
<div class='container mt-2'>
 
<div id="groups">
    <% if @groups.present? %>
      <% @groups.each do |group| %>
      <div class='card'>
      <%= link_to group_expenses_path(group) do %>
        <%= render group %>
    <%end%>
   
    </div>
  <% end %>
    <% else %>
      <h6 class="text-center card"> <i> Category list is empty </i></h6>
    <% end %>
  
 
</div>
</div> 
<div class="button-container">
    <%= link_to "Add a new Group", new_group_path, class: "btn btn custom w-100" %>
</div>
<div >
  <%= button_to "Sign-Out", destroy_user_session_path, method: :delete, class: "btn btn-light w-100"  %>
</div>

app/views/groups/new.html.erb
<h1>Add Group</h1>

<%= render "form", group: @group %>

<br>

app/views/groups/show.html.erb
<div class="container card">
<% if @group.present? %>
  <%= render partial: 'group', object: @group %>
<% end %>
<div class='action' >
  <%= link_to "Edit this group", edit_group_path(@group) %> |
  <%= link_to "Back to groups", groups_path %>

  <%= button_to "Delete", @group, method: :delete, class: 'btn btn-danger' %>
</div>

<div>